Created pds4_create_bundle_member_index.py
SETI/pds-data-projects pull request #34
Opened 2023-02-01 23:39 UTC by esimpsons3ti

2023-02-06 21:44 UTC, rfrenchseti requested changes
- Please provide a description for the pull request to let us know what you've done and if there are any known problems.
- The branch name seems wrong for the task at hand (20-index_tools_direction).
- I have not verified the actual functionality of the program, just its formatting and style. Matt should check the functionality.

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    if not bundle_structure:
I find the variable `bundle_structure` to be confusing. It's a boolean, so when it's True it means what? Maybe something like `is_bundleset` or whatever it's supposed to mean? Actually `is_` is a great prefix for boolean variables.

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +            fullpaths.clear()
Pretty sure `fullpaths` should be a local variable. Then you can just use `fullpaths = []`

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +            bundle_member_index.clear()
Same

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +collections = {}
As mentioned none of these should be global variables. Or if you want to make them global variables, put them in ALL CAPS and then use the `global` modifier to make it clear.

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                    help='State this argument when you are scraping a bundle.')
"State this argument" is odd wording for a help message. Normally you would just say what the argument does: "Indicates that you are scraping a bundle". But you could also make the argument more self-explanatory. Like "--scrape-bundle" or "--is-bundle" or something.

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +parser.add_argument('--bundleset', dest='bundletype',
I don't quite get `bundletype`. Is the `--bundle` argument above supposed to set this to True? Because it doesn't. If you made `bundletype` the dest for `--bundle` then it would work, and you could put the default clause there instead of separately below. But what happens if the user specifies neither? You don't tell them what the default is, and you don't say it's an error not to specify.

2023-02-06 21:44 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +create_bundle_member_index(args.directorypath[0], args.bundletype)
Should have a carriage return at the end of the file (note the big red circle in the GitHub display).

2023-02-07 21:52 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    'The LID does not contain an accepted collection term'
The purpose was to display a message after the exception was raised. It has been moved to its proper location.

2023-02-13 21:51 UTC, matthewtiscareno commented
>     * The branch name seems wrong for the task at hand (20-index_tools_direction).

I think it's true that something like 20-create_bundle_member_index would have been a better branch name.  Is that all you meant to say on this point, @rfrenchseti?  That's a good lesson for the future.  However, I think I've learned that changing branch names is never a good idea, so we should probably just go with what we have, yes?

2023-02-13 21:59 UTC, matthewtiscareno commented
The file `pds4_create_collection_member_index.py` is misplaced in this branch and this pull request.  That file will eventually answer issue #21 and should be placed accordingly.

2023-02-13 22:19 UTC, rfrenchseti commented
> > ```
> > * The branch name seems wrong for the task at hand (20-index_tools_direction).
> > ```
> 
> I think it's true that something like `20-create_bundle_member_index` would have been a better branch name. Is that all you meant to say on this point, @rfrenchseti? That's a good lesson for the future. However, I think I've learned that changing branch names is never a good idea, so we should probably just go with what we have, yes?

Yes, just go with what you have. I was just saying it seemed like the branch was supposed to be only for creating the directory, not actually adding any files to it.

2023-02-13 22:24 UTC, matthewtiscareno commented
> > > ```
> > > * The branch name seems wrong for the task at hand (20-index_tools_direction).
> > > ```
> > 
> > 
> > I think it's true that something like `20-create_bundle_member_index` would have been a better branch name. Is that all you meant to say on this point, @rfrenchseti? That's a good lesson for the future. However, I think I've learned that changing branch names is never a good idea, so we should probably just go with what we have, yes?
> 
> Yes, just go with what you have. I was just saying it seemed like the branch was supposed to be only for creating the directory, not actually adding any files to it.

That branch was [19_index-tools-directory](https://github.com/SETI/pds-data-projects/tree/19_index-tools-directory), and it was merged via pull request #[30](https://github.com/SETI/pds-data-projects/pull/30).  This is is the correct branch, so the only issue is its name.

2023-02-17 19:19 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +create_bundle_member_index(args.directorypath[0], args.bundletype)
Would ending the file with `print('', end='\r\n')` suffice?

2023-02-17 19:38 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +create_bundle_member_index(args.directorypath[0], args.bundletype)
I mean a carriage return at the end of the `.py` file, not the output CSV file. Just make sure you're starting a new line at the bottom of the file.

2023-03-01 19:40 UTC, esimpsons3ti reviewed
I have revised pds4_create_bundle_member_index.py and have added pds4_create_bundle_set_member_index.py. These are ready to review.

2023-03-01 22:34 UTC, rfrenchseti requested changes
I mainly made initial code formatting comments. Matt should run the code and see if it does what he wants. I didn't comment on the second file because all of the comments from the first one carry over.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    """ This exception is raised if a LID does not contain a collection term.
There should not be a space after the `"""`. Please review PEP257 as none of the docstrings are compliant.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    Generates the paths to the correct files, places them in the correct
This comment makes no sense to me. What are the "correct files"? What "dictionary"? What is "the correct spot in the directory". Be explicit.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                                                     namespaces=ns)
This is still a bad indent. The second line has an extra space.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove extra blank line.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                                       remove_blank_text=True))
Indent argument line

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                        'Reference Type':bundle_member.reference_type,
Add space after `:`

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                     fullpaths.append(os.path.join(root, file))
Indent has an extra space

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +            if any(term in lid for term in collection_terms):
I think we talked earlier about not having `pass` be a statement after an if. Simply invert the test instead, like `if not any(...`

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                        print(f'PDS4 label found but not a member of this '
Not fixed

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                        {'LID':lid,
Add space after `:`

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    first_level_subdirectories = next(os.walk(directory_path))[1]
What I meant was the statement `next(os.walk(directory_path))[1]` is weird and it would be nice to explain what you're accomplishing there. It's a good statement, just not immediately obvious what it's doing.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    # The 'first_level_subdirectories' allows for the scraping code to only
Are you trying to say: "We only look at subdirectories one level down from directory_path."? I don't know what this has to do with "fullpath generation remains simple", though.

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +ns = {'pds':'http://pds.nasa.gov/pds4/pds/v1',
Add space after `:` this line only

2023-03-01 22:34 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +print(end='\r')
Again I think there's confusion about what I meant by add a carriage return at the end of the file. I didn't mean print one out. I meant make sure the last line of the program ends with a return. Here's what you see when it doesn't.
![image](https://user-images.githubusercontent.com/6488118/222280768-71fc46cf-35d0-4c8c-8942-634ca17c88e7.png)

2023-03-02 21:23 UTC, esimpsons3ti reviewed
Changes addressed, docstrings fixed. Please re-review.

2023-03-02 22:00 UTC, rfrenchseti requested changes
This is looking pretty good now. I didn't make comments on the second program that were the same as the first. It does seem like your life will be a lot easier when you combine these into the same script.

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                         ['Reference Type'],
This second `[]` should either be placed on the same line above, or indented so it's obvious it is referring to the same thing. It's done better in the other script.

```
variable[a]
        [b]
```

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +"""Create a csv file of a bundle's bundle members and their information.
Does a bundle actually have bundle members? Like a bundle contains other bundles? Maybe this should just be "a bundle's members"?

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +sorted alphabetically by LID and then stores it in the attributed bundle
comma after LID

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +argument, the path to the bundle directory.
Flow on previous line so it formats nicely

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    within the bundle_member_lid dictionary, an error is raised. If a LID
Maybe say an exception is raised instead of an error is raised? You could also say which exception.

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    represented within the bundle, a warning is raised but the file will
How is a warning "raised"? Printed? Exception?

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        function for crossmatching. The input bundlepath is the path to
`bundle_path`

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        the bundle, directory_path.
I'm not sure what `directory_path` means here.

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        Any instance of We only look at subdirectories one level down
I think something got pasted here by accident

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                        print(f'PDS4 label found but not a member of this '
Still not fixed. Just change the first line to:

```
                        print( 'PDS4 label found but not a member of this '
```

(replace the f with a space)

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        that bundle. Input value is the path leading to the bundle.
Instead of "input value" name it explicitly "bundle_location"

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        The input 'subdirectory' will be the path to the bundle directory_path.
The argument is actually called "directory" not "subdirectory"

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    # The 'first_level_subdirectories' allows for the scraping code to only
How about:

```
# 'first_level_subdirectories' contains all of the subdirectories of the top-level directory
# 'directory_path'. This are found by calling the os.walk iterator once and extracting
# the list of directories returned, which will always be at the top level.
```

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
It wouldn't be bad to put some kind of divider here, to indicate the break between functions and the main code. Something like

```
################################################
```

(80 characters wide)

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_set_member_index.py
> +"""Create a csv file of a bundle's bundle members and their information.
Should this say bundle set?

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        bundle_member_lid = {}
ChatGPT points out, correctly, that it is confusing and potentially bad to have a variable `bundle_member_lid` both here and in the parent function, because someone could think that modifications to this local variable were actually changing the one in the parent function.

2023-03-02 22:00 UTC, rfrenchseti commented on indextools/pds4_create_bundle_set_member_index.py
> +                         'Path': fullpath}))
Add one space of indent

2023-03-10 22:15 UTC, matthewtiscareno requested changes
Great progress!  I've made some comments about the PDS4-driven functionality.

2023-03-10 22:15 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +                    if term not in fullpath:
This whole conditional should not be here, I think.  The stated exception (a PDS4 label found in the file structure that is not a bundle member) seems identical to what is currently called BadLID.  However, what is actually found by this conditional is a collection type that matches something in `lid` but not in `fullpath`.  I'm not sure what that means, because the LID should be directly constructed from the path.

2023-03-10 22:15 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +                    bundle_member_index[lid] = (
Ah, now **this** dictionary has the structure you could have been using all along!  Instead of creating a second dictionary at this point, this could be the dictionary you created back when you created `bundle_member_lid`.  At that point, the `LID` field can be filled in as it is here, because you already know it at that point.  Also at that point, create the `Path` field, though it will then be blank.  Then, all you need to do at this point is fill in the `Path` field.

2023-03-10 22:15 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_set_member_index.py
> +"""Create a csv file of a bundle set's members and their information.
Please remove this file from this branch and pull request.  Let's focus on getting `pds4_create_bundle_member_index.py` working and merged.  Once that is done, `pds4_create_bundleset_member_index.py` (please note I've removed a `_` in the filename) will be another step.  Shall we create another issue for the latter?

2023-03-10 22:33 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    file_creator(directory_path)
At this point, after you have finished creating `index_bundle` but before you have invoked `file_creator`, you should check whether there are any bundle member entries that did not have their paths filled in during the previous process.  If it’s a secondary bundle member, then again just print a warning and proceed.  However, if a primary bundle member has no match within the file structure, the error should be fatal.

2023-03-13 22:41 UTC, matthewtiscareno requested changes
Good progress.  A few more things to address.

2023-03-13 22:41 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +                      ' does not contain a file path.')
"does not contain" ==> "has not been matched with"

2023-03-13 22:41 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +                      ' does not have a file path.')
"does not have" ==> "has not been matched with"

2023-03-13 22:41 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +            if lid not in bundle_member_entry_lids.keys():
I'm uncomfortable assuming that the keys to the dictionary are the LIDs.  We might want to change that someday, and if we do, we would break this line (and also Line 113). 

More robust would be to use the 'LID' field in the dictionary as the official repository of LIDs, both here and in Line 113.  Here is how (Rob helped me with this!):
`bundle_member_lids = [bundle_member_index[x]['LID'] for x in bundle_member_index]`

Put the above line wherever you want, so that it will be as generally applicable as `bundle_member_index`.  Then you can use `bundle_member_lids` here in Lines 110 and 113.

2023-03-15 22:24 UTC, matthewtiscareno requested changes

2023-03-15 22:24 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +        return fullpaths
Isn't this unnecessary?

2023-03-15 22:24 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +        return bundle_member_index
Isn't this unnecessary?

2023-03-16 18:56 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        return bundle_member_index
Because bundle_member_index still needs to be callable after this first function, the return statement here is required for the program to work.

2023-03-16 23:13 UTC, matthewtiscareno approved these changes
Very good!  I have verified functionality.

2023-03-17 00:21 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +        return bundle_member_index
I'm not sure about this.  Perhaps @rfrenchseti should take a look.

2023-03-17 00:29 UTC, rfrenchseti requested changes

2023-03-17 16:21 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        return bundle_member_index
I apologize, I confused the term "callable" with the return function's ability to "return the result back to the caller". I will be more careful with these terms. 

The code block itself takes the empty dictionary and fills it with the bundle entry information scraped from a bundle.xml file. I imagine because bundle_member_index is created in create_bundle_members() but also used in index_bundle(), the return statement is required in the former. Without it, the return value on index_bundle() becomes NoneType.

2023-03-28 16:48 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        return bundle_member_index
I have removed the return statement in this function.

2023-04-04 22:18 UTC, rfrenchseti requested changes

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    def create_bundle_members(bundle_path):
It's not worth changing anything, but just some thoughts based on our discussion this morning. Since each of these sub-functions is only called once, and is pretty short, it might actually be more readable to get rid of the sub-functions and just put all this code inline. On the other hand, breaking things into multiple functions does improve testability, but you can't actually take advantage of that when the functions are defined inside another function. There's no way to call these sub-functions from an external testing framework. So if you wanted to write unit tests for them, I would move them to the top-level module scope so you can call them directly. To do that, you would have to get rid of the code that mutates the bundle_member_index and fullpaths variables in the enclosing scope, and instead pass them in as arguments and return them as return values.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        bundle_file_path = []
So later is appears bundle_file_path is supposed to be a string (file path) but here you initialize it to an empty list. If there is no `bundle.xml` file in the directory, then `objectify.parse` will try to open this empty list as a file, which will obviously fail. Perhaps you want to initialize it to `None` here and then check if it still equals `None` after the `for path` loop below, printing an error if so?

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        The path to the bundle.xml file is parsed with lxml.objectify. The
The parameter to this function is not the path to the bundle.xml file itself, but is the path to a directory that might contain the bundle.xml file somewhere under it.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        The break in the loop ensures that os.walk does not go into
Generally the docstring shouldn't have explanations of the internal workings of the code (like this "break" comment). Those should be reserved for comments inside the code itself. The docstring is something read by an external user who wants to know how to use this function, and so only cares about the inputs, outputs, and any side effects.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        raise a terminal message, but keep the file if it otherwise matches.
You raise an exception, not a terminal message. You print or output a terminal message.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        This takes the bundle_member_index dictionary created by index_bundle
No, it takes the bundle_location directory...

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        dictionary is then returned to be referenced in the index_bundle
Actually nothing is returned from this function. Instead bundle_member_index from the enclosing scope is mutated.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +            if lid in bundle_member_lids:
Just say `else:`

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        """Fill the bundle_member_index dictionary with bundle member data.
You say "bundle member data" but it looks like the only thing it's actually doing is setting the path.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    def fullpaths_populate(directory):
I'm confused by the above function taking in "bundle_path" and this taking in "directory". Are they the same thing? If so they should have the same name.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    # top-level directory 'directory_path'. This are found by calling the
This -> These

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    # 'first_level_subdirectories' contains all of the subdirectories of the
This comment should be a few lines lower just before the code you're actually talking about.

2023-04-04 22:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +parser.add_argument('directorypath', type=str, nargs=1,
You can get rid of the `nargs=1` here and then remove the `[0]` below because it will no longer be a list.

2023-04-05 00:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    def create_bundle_members(bundle_path):
@rfrenchseti, please also keep in mind that this is the first of a series of tools. Keeping the functions bite-sized may facilitate them being mixed and matched in future tools.

2023-04-06 21:15 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    def create_bundle_members(bundle_path):
In the interest of keeping things easily separated and adaptable for these future tools, I am electing to keep the code structure as it is.

2023-04-07 00:18 UTC, rfrenchseti requested changes
Please add a requirements.txt file with the minimal set of modules needed (at the very least lxml is non-standard).

2023-04-07 00:18 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +            exit(1)
`sys.exit()` should be used instead of `exit` in a program. See: https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python

2023-04-07 00:20 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +            exit(1)
I meant sys.exit(1). I did not intend to use exit(). I will fix this.

2023-04-10 17:07 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        file_location = os.path.join(directory_path, first_level_subdirectory)
To fix the Windows problem you also have to change this line to not use os.path.join

2023-04-10 17:18 UTC, rfrenchseti approved these changes

2023-04-10 20:03 UTC, merged