Created pds4_create_bundle_set_member_index.py
SETI/pds-data-projects pull request #42
Opened 2023-04-12 21:37 UTC by esimpsons3ti

Scrapes the contents of the bundle.xml file in every bundle within a bundle set, and creates a csv containing the LID, member status, reference type, and filepath (if it exists) of all .xml/.lblx files within the first level of subdirectories of the bundle.

Currently has full functionality.

2023-04-14 20:51 UTC, matthewtiscareno commented
Fixes #37

2023-04-14 20:53 UTC, matthewtiscareno commented
As with volset in PDS3, and as with the title of Issue https://github.com/SETI/pds-data-projects/issues/37 (but, I confess, not in consistent usage within the issue discussion), we should always use "bundleset" as a single word. Please fix this throughout, including in filenames.

2023-04-17 23:52 UTC, matthewtiscareno requested changes

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    bundleset_index = {}
This dictionary should be `bundleset_member_index`, in order to preserve parallelism with `pds4_create_bundle_member_index.py`.  Right?

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    bundleset_name = dirpath.split('/')[-1]
Why `dirpath` here, and not `directory_path` as in `pds4_create_bundle_member_index.py`?

Consistency in things like this will make the restructing job easier later on.

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +def create_bundle_member_index(dirpath):
I don't see a reason for this function to be a function.  It seems that it is specific to this particular tool and will never be reused for anything else.  

Please discuss the pros and cons of taking the content of this function and just putting it down at Line 91 where you call this function. 

The same may be true for the analogous function in `pds4_create_bundle_member_index.py`

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    shortpath = bundleset_name + bundle_path.split(bundleset_name)[-1]
This line could be a function by itself, perhaps called `get_shortpath`

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +def index_bundleset(bundle_path, bundleset_index, bundleset_name):
I think this function should be broken up into several functions, which then you call sequentially at the place where this function is called.  See details below.  This will enhance modularity for when we tackle Issue #36

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    bundle_lid = str(bundle_root.Identification_Area.logical_identifier.text)
This portion should be one function, perhaps called `get_member_lid`

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +        'Path': shortpath})
This portion could be a function called `add_to_index`

2023-04-17 23:52 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +def bundle_file_paths(bundleset_path):
Call this function `get_bundle_filepaths`.  This portion of the task is done differently than for other tools, so it does make sense for it to be in its own function.

2023-04-18 17:18 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +def create_bundle_member_index(dirpath):
Based on Slack conversation, retain this function but rename it `main`.

2023-04-18 18:18 UTC, esimpsons3ti commented on indextools/pds4_create_bundleset_member_index.py
> +    bundleset_index = {}
I agree! It has been changed.

2023-04-18 21:40 UTC, rfrenchseti requested changes
I had started a review before the most recent function reorganization. I'm going to go ahead and post those to clear out my queue, but realize that some may no longer be relevant.

2023-04-19 06:39 UTC, matthewtiscareno requested changes

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    """Populate the bundleset_member_index dictionary with bundle information.
Don't forget to update comments when you update functionality.

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundleset_member_index.py
> +    """Create the bundleset_member_index.csv file for the bundleset."""
It seems like a `main` function doesn't need a description, since it can be assumed that the docstring at the beginning of the file applies to it.

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_set_member_index.py
> +sorted alphabetically by LID, and then stores it in the attributed bundle
I agree that "attributed" is not the word you want here.  However, more importantly, isn't this a description of what you formerly thought this tool was supposed to do, and not what it actually does?

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_set_member_index.py
> +        """Generate a .csv file containing data about the bundle directory.
This comment is obsolete.

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_set_member_index.py
> +                                                    namespaces=ns)
This comment is obsolete for this pull request, though it may apply to pds4_create_bundle_member_index.py

Let's keep it in mind for the future task of retrofitting pds4_create_bundle_member_index.py to fit the changes we're making here.

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_set_member_index.py
> +    def create_bundle_members(bundle_path):
This comment is obsolete.

2023-04-19 06:39 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_set_member_index.py
> +        ny instance of .xml and .lblx files within the first level of
This was a transplanted "Any" from pds4_create_bundle_member_index.py, but now obsolete.

2023-04-19 17:04 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_set_member_index.py
> +                                                    namespaces=ns)
`ns` is not actually utilized in this script, so I am removing it.

2023-04-19 17:19 UTC, esimpsons3ti commented on indextools/pds4_create_bundleset_member_index.py
> +    """Create the bundleset_member_index.csv file for the bundleset."""
According to style guidelines, all functions should have a docstring. However, there is an argument that `main()` is sufficiently described by the module's primary docstring. So I am electing to remove the docstring for `main()`.

2023-04-19 17:22 UTC, rfrenchseti commented on indextools/pds4_create_bundleset_member_index.py
> +    """Create the bundleset_member_index.csv file for the bundleset."""
Yes, I think that's completely reasonable.

2023-04-19 17:45 UTC, merged