Unnested pds4_create_bundle_member_index.py
SETI/pds-data-projects pull request #44
Opened 2023-04-14 23:21 UTC by esimpsons3ti

Unnests pds4_create_bundle_member_index.py. Fixes #43

2023-04-14 23:39 UTC, matthewtiscareno approved these changes
I can confirm that this version preserves functionality.

2023-04-15 01:45 UTC, rfrenchseti requested changes

2023-04-15 01:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    with open(bundle_location + '/bundle_member_index.csv',
This should be os.path.join

2023-04-15 01:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    This takes the bbundle_member_index dictionary created by index_bundle
bbundle -> bundle

2023-04-17 16:52 UTC, rfrenchseti approved these changes

2023-04-17 16:55 UTC, merged