Separated functions within pds4_create_bundle_member_index.py
SETI/pds-data-projects pull request #45
Opened 2023-04-19 20:59 UTC by esimpsons3ti

This code is fully functional and also contains updated docstring style.

2023-04-20 00:31 UTC, rfrenchseti requested changes

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    """Find and store path to the bundle.xml file in the bundle.
Comment is wrong

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    In the event a path to the bundle.xml file is not found, a terminal
Just a comment going forward...since you're planning to make these functions generic and useable by a variety of other programs, I strongly suggest you get rid of anything that prints a message or, especially, exits. A library function should never exit the program. Instead you should throw an exception (with an appropriate message), and then the calling functions should catch the exception and decide what to do with it - print the message and exit, log the message and skip that bundle, whatever. But it should be up to the caller.

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                bundlepath = os.path.join(path, file)
Don't you want to have a `break` here? Right now, after it finds `bundle.xml`, it keeps look through the whole directory structure. In the best case this is really slow. In the worst case it actually finds another file with that name.

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        bundle_path    The path to the bundle directory.
It's really confusing that you have `bundle_path` and `bundlepath`, where the only difference is the underscore. One is a directory, and one is the path including the filename. You could do something like rename the second one to `bundlexml_path` or the first one to `bundle_directory`. Or both.

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    The "Path" section is intentionally left blank. This will be filled in
This comment would make more sense down in the return area.

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +                               will contain the following:
You should say something about the dictionary being mutated. Instead of "will contain the following" say something like "will have the following added to it".

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    ns = {'pds': 'http://pds.nasa.gov/pds4/pds/v1',
Are these namespaces something that will always be permanent here, or that you want the caller to be able to pass in as you support more type of bundles?

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove extra blank line

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove extra blank line

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove extra blank line

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove extra blank line

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        directory_path         The path to the bundle directory
Is this different from "bundle_path" above?

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove blank line

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +            print(f'LID {lid} found in file structure at '
At some point you'll probably want to replace this with some kind of logging support

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +
Remove blank line

2023-04-20 00:31 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    print(bundlepath)
Old debugging code?

2023-04-20 17:53 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    ns = {'pds': 'http://pds.nasa.gov/pds4/pds/v1',
That's a great question, actually. @matthewtiscareno would know.

2023-04-20 17:55 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +        directory_path         The path to the bundle directory
It is not. I will rename it.

2023-04-20 18:07 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +            print(f'LID {lid} found in file structure at '
We are still working on how these functions will work separately. Matt and I will discuss when to implement logging in this development process.

2023-04-20 18:10 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +                bundlepath = os.path.join(path, file)
I agree that adding a `break` would be in good practice.

2023-04-20 18:12 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    """Find and store path to the bundle.xml file in the bundle.
I mean the function literally doesn't do what the comment says. It says it "finds and stores the path", but it doesn't store it anywhere. Perhaps you mean it "finds and returns the path"?

2023-04-20 18:33 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    """Find and store path to the bundle.xml file in the bundle.
You are right, but now I have a phrasing question. Is it acceptable to say that a function 'returns' something if there is no actual return statement?

2023-04-20 18:53 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    """Find and store path to the bundle.xml file in the bundle.
No, but this function does actually return something, doesn't it?

2023-04-20 18:57 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    """Find and store path to the bundle.xml file in the bundle.
Yes it does! My bad.

2023-04-20 18:59 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
> +    The "Path" section is intentionally left blank. This will be filled in
This was what I was thinking of. There is no return area for this function because it doesn't return anything. Should it be a comment above the block of code that populates the dictionary instead?

2023-04-20 20:02 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    ns = {'pds': 'http://pds.nasa.gov/pds4/pds/v1',
Actually a question for @mace-space or @mit3ch

2023-04-20 21:16 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    ns = {'pds': 'http://pds.nasa.gov/pds4/pds/v1',
Actually, every PDS4 header contains a line near the top that specifies the schema that should be used to parse that file.  I've created issue #46 to remind us to do this later.

2023-04-20 21:30 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    In the event a path to the bundle.xml file is not found, a terminal
You make a good point that we eventually want to implement better error-handling.  I've created Issue #47 to remind us to do this.

2023-04-20 21:38 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +            print(f'LID {lid} found in file structure at '
We don't envision this tool being run in such a way as to generate log files worth keeping.  Nevertheless, it is a good point that functions should not print messages, because they lack the context of the caller.  This also falls under the newly created issue #47.

2023-04-20 23:45 UTC, rfrenchseti requested changes

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +    bundlexml_path = None
See discussion on Slack:

I'm confused about the new function get_bundle_filepaths . As far as I can tell, it only returns a single path, so it shouldn't be plural. Also didn't we decide that in this instance you didn't need to do the walk? Finally the break only breaks out of the inner loop (the for file in files). It doesn't break out of the outer loop, which means it will continue to walk the entire directory structure. Assuming it really is only getting a single path, the really easy solution for the latter problem is to just return from inside the loop. There's no reason to set a bundlexml_path variable at all.

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        bundlexml_path               Path to the bundle.xml file
Make Input/Returns indents the same

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        bundle_directory         The path to the bundle directory
Fix indent

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
> +        bundle_directory        Path to the bundle directory.
Fix indent

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
>  def file_creator(bundle_location, bundle_member_index):
Are bundle_location and bundle_directory the same thing?

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundle_member_index.py
>  parser = argparse.ArgumentParser()
I don't think the argument parsing was moved

2023-04-20 23:45 UTC, rfrenchseti commented on indextools/pds4_create_bundleset_member_index.py
> +        bundlexml_paths         The list of paths to all bundle.xml files within
Fix spacing

2023-04-21 15:56 UTC, rfrenchseti approved these changes

2023-04-25 02:17 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    bundlexml_path = None
These are good points, and I think the answer is to shift our thinking about how to generalize the version of `get_bundle_filepaths` in the `bundleset_member_index` tool.  We'll discuss that as we approach Issue #36.

2023-04-25 06:22 UTC, matthewtiscareno approved these changes
Please observe the comments from Rob that I haven't closed, and also my comments.  Whether or not you address them before you merge this PR, you should be sure to address them as you address Issue #36. 

Please be sure to merge master into the branch before you proceed.  That is, the branch currently is 4 commits ahead of master, and you should see that say 0 commits ahead of master before you merge.

2023-04-25 06:22 UTC, matthewtiscareno commented on indextools/pds4_create_bundle_member_index.py
> +    """Scrape the LID from the bundle.xml file.
Does this really describe what this function does?

2023-04-25 17:03 UTC, esimpsons3ti commented on indextools/pds4_create_bundle_member_index.py
>  def file_creator(bundle_location, bundle_member_index):
They are. Bundle_location is now replaced with bundle_directory

2023-04-25 17:32 UTC, esimpsons3ti commented
Okay, this branch has been brought up to speed and can be merged. Should I do it, or should you @matthewtiscareno

2023-04-25 17:59 UTC, merged