Created a collection indexing tool
SETI/pds-data-projects pull request #48
Opened 2023-04-24 19:55 UTC by esimpsons3ti

The code is functional and proofread for mistakes. This has also been structured to be comparable to the other indexing tools.

2023-04-25 05:29 UTC, matthewtiscareno commented
Fixes #21

2023-04-25 06:25 UTC, matthewtiscareno approved these changes
Whether or not you address my comments before you merge this PR, you should be sure to address them as you address Issue https://github.com/SETI/pds-data-projects/issues/36.

This branch currently is 0 commits behind master, so you could go ahead and merge it.  However, if you merge PR #45 first, then this branch will be behind master and you will need to merge master into the branch before you proceed.

2023-04-25 06:25 UTC, matthewtiscareno commented on indextools/pds4-create_collection_index.py
> +This tool takes the input in the form of a path to a collection.xml file. The
It's fine to use `collectionxml` as a filename.  However, in comments you should always say `collection_*.xml`, because that is the form that the name will always actually take.

2023-04-25 06:25 UTC, matthewtiscareno commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
The string `csv` should not actually appear in the code, because the collection product is not required to be a `csv` file (though it commonly is).  In comments you should call it "the collection product" and as a variable you might consider `collectionprod` instead of `collectioncsv`.

2023-05-01 18:41 UTC, esimpsons3ti commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
I would like to confirm that it is still okay to leave in mention of a `csv` file in reference to the index file the code creates. The term `csv` will be removed from variable names and from comments referring to the original collection product.

2023-05-01 18:45 UTC, matthewtiscareno commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
The correct name for the CSV file is "the collection product."  That is, it is a data file that describes the collection.  It is usually a CSV file, but that is not required.

2023-05-01 19:15 UTC, rfrenchseti commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
I feel like @matthewtiscareno answered a different question than @esimpsons3ti asked. I think she wanted to know about the final CSV file that the indexing program creates...the one with all the summary information. That's always a CSV file, right? Since that's what the code is written to produce.

2023-05-01 19:18 UTC, esimpsons3ti commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
Yes, that is what I meant.

2023-05-01 19:29 UTC, esimpsons3ti commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
For now, I can refer to both the original collection product file and the created csv file as 'collection product' files. This terminology can be changed in the master file.

2023-05-01 19:33 UTC, esimpsons3ti commented
Current note about this version of collections.py: currently does not work with uranus_occs_earthbased's xml_schema collections, due to files that share LIDs.

2023-05-01 19:44 UTC, matthewtiscareno commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
Okay, I can see that now and I apologize for misunderstanding.  

Actually, the file being created by this tool is *not* a collection product, so please don't call it that.  My own comment is a great illustration of how using a file's format as its identifier can be confusing!  

Perhaps the file being created by the tool should be called "the output file."

2023-05-01 19:45 UTC, esimpsons3ti commented on indextools/pds4-create_collection_index.py
> +collection's csv file is then scraped for LIDVIDs (separated into LID and VID)
Got it, I will fix this and commit the changes right away.

2023-05-01 19:49 UTC, matthewtiscareno commented
> Current note about this version of collections.py: currently does not work with uranus_occs_earthbased's xml_schema collections, due to files that share LIDs.

I believe the only example is the xml_schema collection of the uranus_occ_support bundle of the uranus_occs_earthbased bundleset.  That collection product lists `urn:nasa:pds:system_bundle:xml_schema:pds-xml_schema` twice, once with VID 1.9 and the other with VID 1.20.   

It seems that xml_schema bundles have no primary members, so I don't know that we will want to make index files for them in any case.  However, I still would like to check with @mit3ch about why this is the way it is.

2023-05-02 21:39 UTC, matthewtiscareno requested changes
A couple minor things

2023-05-02 21:39 UTC, matthewtiscareno commented on indextools/pds4_create_collection_member_index.py
> +    collectionxml_file = args.collectionpath
The input should be the path of the directory that contains the label, not the path to the label.  That's how you did it with the bundle_member_index tool, and it's also what the issue says.

2023-05-02 21:39 UTC, matthewtiscareno commented on indextools/pds4_create_collection_member_index.py
> +                                                                     'VID']))
The VID should immediately follow the LID, which is what it modifies.

2023-05-02 21:41 UTC, matthewtiscareno commented on indextools/pds4_create_collection_member_index.py
> +                                                                     'VID']))
Also, do these lines need to be so indented?

2023-05-02 22:55 UTC, esimpsons3ti commented on indextools/pds4_create_collection_member_index.py
> +    collectionxml_file = args.collectionpath
In the issue it states "Input argument should be described in comment (or docstring?) as the path containing the collection_*.xml file." I must have misinterpreted this. I thought _the path itself_ would contain the collection_*.xml file. I have created a new function to fix this.

2023-05-02 22:57 UTC, esimpsons3ti commented on indextools/pds4_create_collection_member_index.py
> +                                                                     'VID']))
They are indented this way to comply with the 80 character line limit, but I can change the indentation. Let me know what you think of the new version.

2023-05-02 22:58 UTC, matthewtiscareno commented on indextools/pds4_create_collection_member_index.py
> +    collectionxml_file = args.collectionpath
The same wording was used in Issue #20, but I acknowledge that the wording could have been clearer.

2023-05-02 22:59 UTC, matthewtiscareno commented on indextools/pds4_create_collection_member_index.py
> +    collectionxml_file = args.collectionpath
The most important thing is for the tools you're about to unify to do the same thing.

2023-05-02 23:01 UTC, esimpsons3ti commented on indextools/pds4_create_collection_member_index.py
> +    collectionxml_file = args.collectionpath
The new function is almost a clone of `get_bundle_filepaths` in the bundle_member_index tool. Of course the variable names are different, but those will change in the unified version of the function.

2023-05-02 23:03 UTC, rfrenchseti commented on indextools/pds4_create_collection_member_index.py
> +                                                                     'VID']))
I think the issue is `fieldnames` is over-indented. It should be under `index_file`.

2023-05-02 23:04 UTC, esimpsons3ti commented on indextools/pds4_create_collection_member_index.py
> +    collectionxml_file = args.collectionpath
> The same wording was used in Issue #20, but I acknowledge that the wording could have been clearer.

We had a verbal discussion about bundleset_member_index where you confirmed where the path should go. I suppose my understanding didn't extend to this program.

2023-05-02 23:06 UTC, esimpsons3ti commented on indextools/pds4_create_collection_member_index.py
> +                                                                     'VID']))
@rfrenchseti I agree, thank you for catching that. However, is this also acceptable:

```
def file_creator(collection_directory, collection_member_index):
    """Create an output file out of collection_member_index.

    Inputs:
        collection_directory       The path to the collection.

        collection_member_index    The dictionary of collection information.
    """
    with open(os.path.join(collection_directory, 'collection_member_index.csv'),
              mode='w') as index_file:
        collection_member_indexer = csv.DictWriter(
            index_file,
            fieldnames=([
                'LID',
                'VID', 
                'Member Status',
                'Path'
                ]))
        collection_member_indexer.writeheader()
        for index in sorted(collection_member_index):
            collection_member_indexer.writerow(collection_member_index[index])
```

2023-05-02 23:07 UTC, rfrenchseti commented on indextools/pds4_create_collection_member_index.py
> +                                                                     'VID']))
Yes, that's perfectly fine as well

2023-05-02 23:20 UTC, merged